name: Jelle
favicon: null
layout_spectrum: 0.8251214276533574
typography_spectrum: 0.6552253593690693
title: "Jelle's travel blog"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#76a3f1'
    - '#acd6fd'
    - '#04070c'
    - '#fefefe'
    - '#5d5d5d'
  brandStrength: 0.9375
  lightness: 0.18465768126770854
  saturation: 0.4375
  rhythmicContrast: 0.28737920988351107
purpose: []
