name: Jelle
favicon: null
layout_spectrum: 1
typography_spectrum: 0.75157
title: "Jelle's travel blog"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f1f1f1'
    - '#292c31'
    - '#d4aa9c'
    - '#7d463f'
    - '#436542'
  brandStrength: 0.5
  lightness: 0.3125
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
