name: Jelle
favicon: null
layout_spectrum: 0.74278
typography_spectrum: 0.75157
title: "Jelle's travel blog"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#43474a'
    - '#99c7f2'
    - '#7e9fa1'
    - '#fdb081'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
